### ISSUE TITLE
Angular 12 Update?

### ISSUE THREAD

**Issue by reflexdemon** [moritzvieli/ngx-bootstrap-slider#26]
Are you planning to provide update for Angular 12 and other new versions of Angular? I am planning to use it in Angular 12 project. Has anyone tried it with latest angular?

**Comment by vinh-silicon** [comment]
@reflexdemon  I've tried to upgrade to angular12 and everything still good until now.

**Comment by reflexdemon** [comment]
Thanks. Will try and let you know if I run into issues.
