### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by paskalov** [moritzvieli/ngx-bootstrap-slider#29]
Hi, can please someone from the maintainers add a license to this repository? 
According to this https://choosealicense.com/no-permission/, if there is no license specified, then the code is under exclusive copyright by default. Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation.

**Comment by moritzvieli** [comment]
@paskalov Just merged your PR. Thanks a lot for it!

**Comment by paskalov** [comment]
@moritzvieli no problem, thank you for merging :)
